apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-poller
spec:
  type: {{ .Values.poller.service.type }}
  ports:
  - port: {{ .Values.poller.service.port }}
    targetPort: {{ .Values.poller.service.port }}
  selector:
    app: cloud-cost-poller 