apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cost-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-cost-poller
  template:
    metadata:
      labels:
        app: cloud-cost-poller
    spec:
      containers:
      - name: poller
        image: yourrepo/cloud-cost-poller:latest
        env:
        - name: AWS_ROLES
          value: "arn:aws:iam::123456789012:role/Role1,arn:aws:iam::123456789012:role/Role2"
        - name: POSTGRES_HOST
          value: "your-postgres-host"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "your-db"
        - name: POSTGRES_USER
          value: "your-user"
        - name: POSTGRES_PASSWORD
          value: "your-password" 