dashboard:
  image: yourrepo/cloud-cost-dashboard:latest
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8501
  env:
    POSTGRES_HOST: your-postgres-host
    POSTGRES_PORT: "5432"
    POSTGRES_DB: your-db
    POSTGRES_USER: your-user
    POSTGRES_PASSWORD: your-password

poller:
  image: yourrepo/cloud-cost-poller:latest
  service:
    type: ClusterIP
    port: 80
  env:
    AWS_ROLES: arn:aws:iam::123456789012:role/Role1,arn:aws:iam::123456789012:role/Role2
    POSTGRES_HOST: your-postgres-host
    POSTGRES_PORT: "5432"
    POSTGRES_DB: your-db
    POSTGRES_USER: your-user
    POSTGRES_PASSWORD: your-password 