apiVersion: v2
name: cloud-cost-compass
description: Multi-tenant cloud cost analysis platform
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: vault
    version: 0.32.0
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled
  - name: keycloak
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled
  - name: cloudnative-pg
    version: 1.0.11
    repository: https://charts.bitnami.com/bitnami
    condition: cloudnative-pg.enabled