{{- if and .Values.keycloak.enabled .Values.keycloak.realmImport .Values.keycloak.realmImport.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.keycloak.realmImport.filename }}: |
{{ .Files.Get "keycloak/ccc-realm.json" | indent 4 }}
{{- end }}