{{- if and .Values.postgres.enabled (index .Values "cloudnative-pg").enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: postgres
  password: postgres
  dbname: cccdb
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.cluster.spec.instances | default 1 }}
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  {{- if .Values.postgres.cluster.spec.storage }}
  storage:
    size: {{ .Values.postgres.cluster.spec.storage.size }}
    storageClass: {{ .Values.postgres.cluster.spec.storage.storageClass }}
  {{- end }}
  {{- if .Values.postgres.cluster.spec.resources }}
  resources:
    {{- toYaml .Values.postgres.cluster.spec.resources | nindent 4 }}
  {{- end }}
  bootstrap:
    initdb:
      database: cccdb
      owner: postgres
  {{- if .Values.postgres.cluster.spec.backup }}
  backup:
    enabled: {{ .Values.postgres.cluster.spec.backup.enabled }}
    retentionPolicy: {{ .Values.postgres.cluster.spec.backup.retentionPolicy }}
  {{- end }}
{{- end }}
